name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.9
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.7.1
  riverpod_generator: ^2.4.0
  source_gen: ^1.5.0

flutter:
  uses-material-design: true
